config/routes.rb
Rails.application.routes.draw do
  root 'attractions#index'

  resources :attractions, :except => :show do
    collection do
      get '/past', action: 'past', as: 'past'
    end
  end
  
  resources :users, only: [:new, :create, :destroy, :index] do
    member do
      get '/attractions',    action: 'attractions', as: 'attractions'
      get '/confirm/:token', action: 'confirm',     as: 'confirm'
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, Attraction
    can :manage, Attraction, user_id: user.id
  end
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :media

  scope :coming, ->{ where('day >= ?', Time.now).order(:day) }
  scope :past,   ->{ where('day < ?', Time.now).order(:day => :desc)  }

  delegate :nick_name, :email, :to => :user, prefix: true
end

app/models/email_confirmation_guard.rb
class EmailConfirmationGuard < Clearance::SignInGuard
  def call
    return next_guard if confirmed?

    failure("You must confirm your email address.")
  end

  private

  def confirmed?
    signed_in? and current_user.confirmed?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :attractions
  after_create :send_confirmation_email
  before_create :set_confirmation_token

  def confirm token
    return unless token == self.confirmation_token

    update_attributes confirmed_at: Time.now
  end

  def confirmed?
    not confirmed_at.nil?
  end

  private 

  def set_confirmation_token
    self.confirmation_token = Clearance::Token.new
  end

  def send_confirmation_email
    UserMailer.welcome_mail( self ).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :forbidden }
      format.html { redirect_to attractions_path, :alert => exception.message }
    end
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:edit, :update, :destroy]
  before_action :require_login, :except => :index

  authorize_resource

  def new
    @attraction = Attraction.new
  end

  def create
    @attraction      = Attraction.new attraction_params
    @attraction.user = current_user

    return success_redirect if @attraction.save

    render :new
  end

  def edit
  end

  def update
    if @attraction.update_attributes( attraction_params )
      success_redirect
    else
      render :edit
    end
  end

  def destroy
    @attraction.destroy

    success_redirect
  end

  def index
    @attractions   = current_user.attractions.coming.includes(:user) if signed_in?
    @attractions ||= Attraction.coming.includes(:user)
  end

  def past
    @attractions = current_user.attractions.past.includes(:user)
  end

  private

  def set_attraction
    @attraction = Attraction.find params[:id]
  end

  def attraction_params
    params.require(:attraction).permit(
        :title, :media, :day, :description
    )
  end

  def success_redirect
    action = params[:action]
    title  = @attraction.try :title
    notice = I18n.t "attractions.messages.#{ action }.success", title: title, default: ''

    redirect_to attractions_path, notice: notice
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :set_user, :only => [:attractions, :confirm]

  def index
    @users = User.all.includes(:attractions)
  end

  def attractions
    @attractions = @user.attractions.coming
  end

  def confirm
    @user.confirm params[:token]

    message   = I18n.t('flashes.success_after_confirm') if @user.confirmed?
    message ||= I18n.t('flashes.failure_after_confirm')

    redirect_to sign_in_path, notice: message
  end

  private

  def url_after_create
    flash[:notice] = I18n.t('flashes.success_after_create')

    attractions_path
  end

  def user_from_params
    User.new(user_params)
  end

  def user_params
    params.require(:user).permit(:email, :password, :nick_name)
  end

  def set_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def brand_link args = {}
    link_text   = 'Suas Atrações' if signed_in?
    link_text ||= 'Atrações'

    link_to link_text, attractions_path, args
  end

  def session_link
    return link_to('Entrar', sign_in_path) unless signed_in?
    
    link_to( "Olá #{current_user.nick_name}, Sair", sign_out_path, :method => :delete )
  end

  def sign_up_link
    link_to t('helpers.submit.user.create'), sign_up_path unless signed_in?
  end

  def alert_class type
    type_class = {
      'success' => 'alert-success',
      'error'   => 'alert-danger',
      'alert'   => 'alert-warning',
      'notice'  => 'alert-success'
    }[type.to_s]

    type_class ||= 'alert-info'
    "alert #{type_class}"
  end
end

app/helpers/attraction_helper.rb
module AttractionHelper
  def link_to_user_attractions attraction, args = {}
    return unless attraction.user

    nick_name   = attraction.user_email if attraction.user_nick_name.to_s.empty?
    nick_name ||= "@#{ attraction.user_nick_name }"

    link_to nick_name, attractions_user_path( attraction.user_id ), args
  end

  def attraction_actions_links attraction
    edit_attraction_link(attraction).concat( delete_attraction_link(attraction) )
  end

  private

  def edit_attraction_link attraction
    return '' unless can? :edit, attraction

    link_to edit_attraction_path( attraction ) do
            content_tag(:span, nil, class: 'fa fa-edit')
    end 
  end

  def delete_attraction_link attraction
    return '' unless can? :destroy, attraction

    link_to attraction_path( attraction ),
      :method => :delete,
      data: { confirm: "Você tem certeza?" } do
            content_tag(:span, nil, class: 'fa fa-trash-o')
    end
  end
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= brand_link class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= content_tag( :li, link_to( 'Attrações passadas', past_attractions_path ) ) if signed_in? %>
        <li>
          <%= link_to 'Usuários', users_path %>
        </li>
        <%= content_tag( :li, link_to( 'Nova Atração', new_attraction_path ) ) if signed_in? %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= session_link %>
        </li>
        <li>
          <%= sign_up_link %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/attractions/_form.html.erb
<%= form_for attraction, html: { class: 'form-horizontal' }  do |f| %>
  <%= render 'shared/errors', messages: attraction.errors.full_messages %>

  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :media, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :media, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :day, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :day, class: 'form-control', placeholder: 'mm/dd/yyyy hh:mm' %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<%= render 'form', attraction: @attraction %>

app/views/attractions/new.html.erb
<%= form_for @attraction do |f| %>
  <div>
    <ul>
      <% @attraction.errors.full_messages.each do |error| %>
        <%= content_tag :li, error %>
      <% end %>
    </ul>
  </div>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :media %>
  <%= f.text_field :media %>

  <%= f.label :day %>
  <%= f.text_field :day %>

  <%= f.submit %>
<% end %>

app/views/attractions/past.html.erb
<%= render '/shared/attractions_list', attractions: @attractions %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrganizacaoDeAtracao</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<%= render 'nav' %>

<div class='container'>

    <% flash.each do |type, message| %>
      <div class="<%= alert_class(type) %>">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>

  <%= yield %>
<div>

</body>
</html>

app/views/shared/_attractions_list.html.erb
<div  id="attractions" class="row">

<% attractions.each do |attraction| %>
  <div class="attraction col-md-4 col-sm-12">
    <div class="attraction-body">
      <div class='attraction-head'>
        <div class='clearfix'>
        <%= content_tag :h4, attraction.title, class: 'attraction-title' %>
        <div class="attraction-actions">
          <%= attraction_actions_links attraction %>
        </div>
        </div>
      </div>
      <div class="attraction-content">
        <div class="clearfix">
          <%= content_tag :p, attraction.media, class: 'attraction-media' %>
          <%= content_tag :p, l(attraction.day, :format => :long), class: 'day' %>
        </div>
        <%= content_tag :p, attraction.description, class: 'attraction-description' %>
      </div>
      <div class="attraction-bottom">
        <%= link_to_user_attractions attraction, class: 'nick-name' %>
      </div>
    </div>
  </div>
<% end %>

</div>

app/views/shared/_errors.html.erb
<div class='container'>

<% messages.each do |error| %>
  <div class="<%= alert_class(:error) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= error %>
  </div>
<% end %>

<div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :nick_name, class: 'col-sm-2 control-label' %>
  <div class="form-group">
    <%= form.text_field :nick_name %>
  </div>
</div>

<div class="text-field">
  <%= form.label :email, class: 'col-sm-2 control-label' %>
  <div class="form-group">
    <%= form.text_field :email, type: 'email' %>
  </div>
</div>

<div class="password-field">
  <%= form.label :password, class: 'col-sm-2 control-label' %>
  <div class="form-group">
    <%= form.password_field :password %>
  </div>
</div>

app/views/users/attractions.html.erb
<%= render '/shared/attractions_list', attractions: @attractions %>

app/views/users/index.html.erb
<div  id="users-list" class="row">
  <% @users.each do |user| %>
    <div class="attraction col-sm-12">
      <div class="attraction-body">
        <div class='attraction-head'>
          <div class='clearfix'>
            <%= content_tag :h4, user.nick_name, class: 'attraction-title' %>
            <div class="attraction-actions">
              <span class="badge"><%= user.attractions.count %></span>
            </div>
          </div>
        </div>
        <div class="attraction-content">
          
            <% user.attractions.each do | attraction |%>
              <div class="attractions-user row">
                <div class="col-md-3"><%= content_tag :p, attraction.title %></div>
                <div class="col-md-5"><%= content_tag :p, attraction.description %></div>
                <div class="col-md-3"><%= content_tag :p, l(attraction.day, :format => :long) %></div>
                <div class="col-md-1"><span class="badge"><%= content_tag :p, attraction.media %></span></div>
              </div>
            <% end %>
            <div class="attractions-user row">
              <div class="col-md-12 see-more" style="">
                <%= link_to 'PÁGINA DO USUÁRIO', attractions_user_path(user) %>
              </div>
              
            </div>
          
        </div>
        <div class="attraction-bottom">
          <%= user.email %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user, html: { class: 'form-horizontal' } do |form| %>
    <%= render 'shared/errors', messages: @user.errors.full_messages %>

    <%= render partial: '/users/form', object: form %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit %>
      </div>
    </div>

    <div class="other-links form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
    </div>
  <% end %>
</div>